---
version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: docker
    steps:
      - setup_remote_docker
      - checkout
      - run: |
          docker image build -t theasp/fluentd-plugins:certified -f Dockerfile-certified .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push theasp/fluentd-plugins:certified
      - run: |
          docker image build -t theasp/fluentd-plugins:slim -f Dockerfile-slim .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push theasp/fluentd-plugins:slim
      - run: |
          docker image build -t theasp/fluentd-plugins:common -f Dockerfile-common .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker tag theasp/fluentd-plugins:common theasp/fluentd-plugins:latest
          docker push theasp/fluentd-plugins:common
          docker push theasp/fluentd-plugins:latest


workflows:
  version: 2
  commit:
    jobs:
      - build
  weekly:
    triggers:
      - schedule:
          cron: "0 12 0 * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
