---
version: 2
jobs:
  build:
    docker:
      - image: docker
    steps:
      - setup_remote_docker
      - checkout
      - run: |
          docker image build -t theasp/fluentd-plugins:certified -f Dockerfile-certified .
          docker image build -t theasp/fluentd-plugins:slim -f Dockerfile-slim .
          docker image build -t theasp/fluentd-plugins:common -f Dockerfile-common .
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
              docker tag theasp/fluentd-plugins:common theasp/fluentd-plugins:latest
              docker push theasp/fluentd-plugins:certified
              docker push theasp/fluentd-plugins:slim
              docker push theasp/fluentd-plugins:common
              docker push theasp/fluentd-plugins:latest
            fi

workflows:
  version: 2
  commit:
    jobs:
      - build
  weekly:
    triggers:
      - schedule:
          cron: "0 12 2 * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
