---
version: 2
jobs:
  build-common:
    docker:
      - image: docker
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run: docker image build -t theasp/fluentd-plugins:common -f Dockerfile-common .

  build-all:
    docker:
      - image: docker
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run: docker image build -t theasp/fluentd-plugins:all -f Dockerfile-all .

  deploy:
    docker:
      - image: docker
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push theasp/fluentd-plugins:common
          docker push theasp/fluentd-plugins:all

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build-common
      - build-all
      - deploy:
          requires:
            - build-common
            - build-all
