name: pipeline
on: [push]
jobs:
  test:
    name: acceptance-test
    runs-on: ubuntu-latest
    steps:
    - name: checkout master
      uses: actions/checkout@master
    - name: test
      uses: cedrickring/golang-action@1.3.0
      with:
        args: make test
      env:
        GO111MODULE: "on"
